// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAY7dfGAQPIn-gfFApXHEP0hLMTk9PEQ4E',
    appId: '1:1064672488045:web:5d0eaa4eb944309b392d64',
    messagingSenderId: '1064672488045',
    projectId: 'agri-connect-app-4556',
    authDomain: 'agri-connect-app-4556.firebaseapp.com',
    storageBucket: 'agri-connect-app-4556.firebasestorage.app',
    measurementId: 'G-RXFML28V3C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbOXpNMxC7j15ydst6yunH1tugTmJ5GCI',
    appId: '1:1064672488045:android:5269d8bd2cfde349392d64',
    messagingSenderId: '1064672488045',
    projectId: 'agri-connect-app-4556',
    storageBucket: 'agri-connect-app-4556.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaY7OFKwkdtjybKIPYRfk-98hshw9Dv9A',
    appId: '1:1064672488045:ios:a56857d440b015e5392d64',
    messagingSenderId: '1064672488045',
    projectId: 'agri-connect-app-4556',
    storageBucket: 'agri-connect-app-4556.firebasestorage.app',
    iosBundleId: 'com.microcode.agriConnectApp',
  );
}
